# config.yml

backend:
  name: git-gateway
  branch: gh-pages # Branch to update (optional; defaults to master)
media_folder: 'assets/uploads'
collections:
  - name: 'blog'
    label: 'Blog'
    folder: '_posts/'
    fields:
      - { name: Title }

  - label: "Pages"
    name: "pages"
    editor:
      preview: false
    files:
      - label: "Home"
        name: "index"
        file: "index.md"
        fields:
          - {label: Headshot, name: headshot, widget: image}
          - {label: Bio, name: bio, widget: markdown}
          - {label: Contact, name: contact, widget: markdown}
          - label: "Social Links"
            name: "social_links"
            widget: 'list'
            fields:
              - label: "link"
                name: "link"
                widget: object
                fields:
                  - {label: link-url, name: url, widget: string }


          - label: Education
            name: education
            widget: list
            fields:
              - {label: Item, name: item, widget: string}
              # - {label: Position, name: position, widget: string}
              # - {label: Photo, name: photo, widget: image}