# config.yml

backend:
  name: git-gateway
  branch: master # Branch to update (optional; defaults to master)
media_folder: 'assets/uploads'
collections:
  - name: 'blog'
    label: 'Blog'
    folder: '_posts/'
    fields:
      - { name: Title }

  - label: "Pages"
    name: "pages"
    files:
      - label: "Home"
        name: "index"
        file: "index.md"
        preview: false
        fields:
          - {label: Bio, name: bio, widget: markdown}
          - {label: Headshot, name: headshot, widget: image}
          - {label: Links, name: links, widget: string}
          - {label: Contact, name: contact, widget: markdown}
          - label: Education
            name: education
            widget: list
            fields:
              - {label: Item, name: item, widget: string}
              # - {label: Position, name: position, widget: string}
              # - {label: Photo, name: photo, widget: image}